### ISSUE TITLE
[Bug]: App reliably crashes on click of 'Default Locale' in the settings menu 

### ISSUE THREAD

**Issue by w2sv** [Pool-Of-Tears/GreenStash#130] opened 2024-05-11 09:36 UTC
### Steps to reproduce

Go to the settings menu, click on 'Default Locale' 

### Expected behaviour

No crash

### Actual behaviour

Crash

### Device name

Xiaomi Redmi Note 10a

### Android version

Android 13

### GreenStash version

3.6.0

**Comment by starry-shivam** [comment] 2024-05-11 09:39
Please update your comment with relevant logs, the app includes a recovery screen which will appear in the event of crash and from there you can easily copy and paste logs when creating bug reports.

**Comment by w2sv** [comment] 2024-05-11 11:29
There's no recovery screen bro.

**Comment by w2sv** [comment] 2024-05-11 11:30
At least not for me

**Comment by starry-shivam** [comment] 2024-05-11 12:00
I'm unable to reproduce this problem in either Android 13 or 14. The app doesn't support changing locale below that yet. If you're not seeing a crash screen, please add a screen recording so I can try to figure out what might be causing the issue. Since you're able to reliably reproduce the error, it's important to provide additional information such as logs or other context. Otherwise, I'll have to close the issue for the time being until someone else reports it with enough details.

**Comment by w2sv** [comment] 2024-05-11 15:46
https://photos.app.goo.gl/CVDauWQboDHtoTyP9

**Comment by starry-shivam** [comment] 2024-05-11 15:53
> https://photos.app.goo.gl/CVDauWQboDHtoTyP9

![Screenshot_2024-05-11-21-22-44-439_com google android apps photos](https://github.com/Pool-Of-Tears/GreenStash/assets/58552395/27dc94bc-0dc7-4834-963c-f14994d47d5a)

**Comment by w2sv** [comment] 2024-05-11 15:54
Alright, give me a sec.

**Comment by starry-shivam** [comment] 2024-05-11 15:54
Just so you know, you can upload the screen recording directly here on GitHub instead of using any third party service.

**Comment by starry-shivam** [comment] 2024-05-11 16:01
Try https://send.vis.ee then

**Comment by w2sv** [comment] 2024-05-11 16:05
https://github.com/Pool-Of-Tears/GreenStash/assets/36566555/e3584954-fd5f-4257-b68e-1ab7529bbc93

Compression helps too

**Comment by w2sv** [comment] 2024-05-11 16:08
My guess is it has something to do with MIUI, maybe it doesn't (yet) support app specific language configuration at all? I don't have too good of an idea of that yet, haven't yet implemented that in any of my apps.

**Comment by w2sv** [comment] 2024-05-11 16:09
Yeah, seems like it. See https://xiaomi.eu/community/threads/miui-14-per-app-language-support.69022/

**Comment by starry-shivam** [comment] 2024-05-11 16:10
> WhatsApp.Video.2024-05-11.at.18.02.46.mp4 
> Compression helps too

Can you click on "view summary" and send me that ss or either copy paste it if it's possible? Because there it'll show actual logs of crash.

**Comment by w2sv** [comment] 2024-05-11 16:14
> > WhatsApp.Video.2024-05-11.at.18.02.46.mp4
> > Compression helps too
> 
> Can you click on "view summary" and send me that ss or either copy paste it if it's possible? Because there it'll show actual logs of crash.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:82)
	at android.app.Activity.performCreate(Activity.java:8523)
	at android.app.Activity.performCreate(Activity.java:8487)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	... 12 more

**Comment by starry-shivam** [comment] 2024-05-11 16:16
> > > WhatsApp.Video.2024-05-11.at.18.02.46.mp4
> > > Compression helps too
> > 
> > 
> > Can you click on "view summary" and send me that ss or either copy paste it if it's possible? Because there it'll show actual logs of crash.
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8296) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:82) at android.app.Activity.performCreate(Activity.java:8523) at android.app.Activity.performCreate(Activity.java:8487) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815) ... 12 more

Damn, MIUI is going to be MIUI, I guess. Even if it's one of the [highlighting features of Android 13](https://developer.android.com/guide/topics/resources/app-languages), Xiaomi is out there, busy breaking standard Android APIs again... Although i use xiaomi myself but my device is currently running hyper os with android 14 where this seems to have fixed.

**Comment by w2sv** [comment] 2024-05-11 16:19
> > > > WhatsApp.Video.2024-05-11.at.18.02.46.mp4
> > > > Compression helps too
> > > 
> > > 
> > > Can you click on "view summary" and send me that ss or either copy paste it if it's possible? Because there it'll show actual logs of crash.
> > 
> > 
> > java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8296) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:82) at android.app.Activity.performCreate(Activity.java:8523) at android.app.Activity.performCreate(Activity.java:8487) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815) ... 12 more
> 
> Damn, MIUI is going to be MIUI, I guess. Even if it's one of the [highlighting features of Android 13](https://developer.android.com/guide/topics/resources/app-languages), Xiaomi is out there, busy breaking standard Android APIs again... Although i use xiaomi myself but my device is currently running hyper os with android 14 where this seems to have fixed.

Yeah I know, but I mean what would Android dev be if you didn't need to handle hundreds of edge cases for each device manufacturer 🙃

**Comment by w2sv** [comment] 2024-05-11 16:20
In any case, I think I'd just catch the exception in the onClick and thereupon show a toast/Snackbar, saying something along the lines of "your device doesn't support app-specific language configuration".

**Comment by starry-shivam** [comment] 2024-05-11 16:27
> In any case, I think I'd just catch the exception in the onClick and thereupon show a toast/Snackbar, saying something along the lines of "your device doesn't support app-specific language configuration".

No, you can't really 'catch' this exception because the crash doesn't happen within the app's process, but outside of it within the internal system component of MIUI itself. If it was happening within the app, the app would've shown you the recovery screen and logs, as I said in my first message. It wasn't able to do so in this case because, well, the crash didn't happen within the app. The most I can do from my side is to figure out somehow if the user is running MIUI, then don't show this option in settings, same as how it doesn't show up if you're running Android 12 or below.

**Comment by w2sv** [comment] 2024-05-11 17:49
Okay I see, that's annoying

**Comment by w2sv** [comment] 2024-05-11 17:59
I've found this gist for checking whether a device is running MIUI, although it really doesn't strike me as a particularly safe or reliable way of doing so

https://gist.github.com/Muyangmin/e8ec1002c930d8df3df46b306d03315d

Really lovely of them to force you to include something like that into your code.

**Comment by starry-shivam** [comment] 2024-05-11 18:04
> I've found this gist for checking whether a device is running MIUI, although it really doesn't strike me as a particularly safe or reliable way of doing so

Yeah, it isn't. According to this method, the option to change the app locale will also get removed from my device, which is running on Hyper OS and where this feature clearly works well.

![Screenshot_2024-05-11-23-31-11-025_com termux](https://github.com/Pool-Of-Tears/GreenStash/assets/58552395/61274ef7-5bf4-4fbc-9b8f-849ecaa2d9a6)

**Comment by starry-shivam** [comment] 2024-05-11 18:10
![Screenshot_2024-05-11-23-38-41-543_com termux](https://github.com/Pool-Of-Tears/GreenStash/assets/58552395/062e53c5-ad4c-4ed4-b9ae-3db154a01bb2)


I don't see any hyper os or miui 15 specific values in `build.prop` to cross check and verify that device is only running miui and not hyper os 😐

**Comment by w2sv** [comment] 2024-05-11 18:21
I mean you do get the MIUI version number under [ro.miui.ui.version.code], which for me is 14
![Screenshot_2024-05-11-20-19-27-146_com termux-edit](https://github.com/Pool-Of-Tears/GreenStash/assets/36566555/97d5ac28-534a-4361-bfc3-1f063b174025)

Maybe the version always differs if it's hyperOS, as is the case for you, so you could possibly disable it only if the version is 14?

**Comment by starry-shivam** [comment] 2024-05-11 18:25
> I mean you do get the MIUI version number under [ro.miui.ui.version.code], which for me is 14 ![Screenshot_2024-05-11-20-19-27-146_com termux-edit](https://private-user-images.githubusercontent.com/36566555/329805943-97d5ac28-534a-4361-bfc3-1f063b174025.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTIxMDIsIm5iZiI6MTcxNTQ1MTgwMiwicGF0aCI6Ii8zNjU2NjU1NS8zMjk4MDU5NDMtOTdkNWFjMjgtNTM0YS00MzYxLWJmYzMtMWYwNjNiMTc0MDI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNDliOWViMDZiMGYxMzkyOTM4OWQ0NWNlYjQ3OWUzNThiNDQ5YWFmNGEzYWIxMjdiMzMwY2MzM2I2ZGI1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NK_b20os5tehUsK4LseLHNVGSyJk67eDY-angnI6o-8)
> 
> Maybe the version always differs if it's hyperOS, as is the case for you, so you could possibly disable it only if the version is 14?

Actually i think i found a more reliable way to figure out weather the device is running only miui and not hyperos, can you try this command and show output (if any) `getprop | grep ro.mi.os`

**Comment by w2sv** [comment] 2024-05-11 18:31
![Screenshot_2024-05-11-20-29-07-329_com termux~2](https://github.com/Pool-Of-Tears/GreenStash/assets/36566555/7ca33243-33ea-4ef9-9fca-6e935ea70aa8)

I get nothing.

**Comment by starry-shivam** [comment] 2024-05-11 18:39
> ![Screenshot_2024-05-11-20-29-07-329_com termux~2](https://private-user-images.githubusercontent.com/36566555/329806612-7ca33243-33ea-4ef9-9fca-6e935ea70aa8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTI3MjAsIm5iZiI6MTcxNTQ1MjQyMCwicGF0aCI6Ii8zNjU2NjU1NS8zMjk4MDY2MTItN2NhMzMyNDMtMzNlYS00ZWY5LTlmY2EtNmU5MzVlYTcwYWE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4MzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YzZlNzg4Y2ZhMDAwYmVmMTgzNWRhMDMwODI5ZDdkZWE3NzE1ZjgyZGZiMzI2ZDBlYzExMjgyYWNlZWJjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fonkleftr_cdr2Y3ouDAzp-4dDSl8Ucwlfs44b5oakc)
> 
> I get nothing.

Thanks! It seems `grep ro.mi.os` is only available in hyperos as mi internally calls hyperos just "OS" and the current version is OS1.0 instead of something like `MIUIXX'

![IMG_20240512_000810_832](https://github.com/Pool-Of-Tears/GreenStash/assets/58552395/d484dd2d-e056-4a93-94bb-b092b3958d58)


I can combine this with standerd miui check to ensure that i dont block devices running hyperos from this feature.

**Comment by w2sv** [comment] 2024-05-11 18:44
Great 😅
Still such an incredibly hacky solution, but better than no solution.

**Comment by starry-shivam** [comment] 2024-05-11 18:47
Exactly, we should thank xiaomi for that 🙂

**Closed** 2024-05-12 07:41 UTC
Labels: bug
